[package]
edition = "2021"
name = "tagame"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.1.11", features = ["derive"]}
